### ISSUE TITLE
Could not load file or assembly 'StackExchange.Redis.StrongName, Version=1.2.6.0,

### ISSUE THREAD

**Issue by YeLin25789** [hylsabella/Easy.NetCore#1]
您好，我将您的功能融入我的架构，运行时报错
System.Reflection.ReflectionTypeLoadException:“Unable to load one or more of the requested types.
Could not load file or assembly 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46'. 系统找不到指定的文件。”

项目中，我只引用了StackExchange.Redis，映射的时候报这个错误。找了很多文章都没解决根本问题，还请指教问题出在哪里~

**Comment by hylsabella** [comment]
可以看看您自己项目中引用的StackExchange.Redis组件版本和Easy.NetCore中的是否一致，因为Easy.NetCore目前引用的是最先版本，而报错的StackExchange.Redis.StrongName, Version=1.2.6.0，是2017年的版本了，2个项目要是dll版本不一致，有可能出现这个问题

**Comment by YeLin25789** [comment]
好的，谢谢，我在研究下~

**Comment by hylsabella** [comment]
有问题我可以帮你解决，Redis相关代码最近会重构一下，同时支持同步和异步模式

**Comment by YeLin25789** [comment]
非常感谢！
现在有出现另外一个问题，关于autoface的
在执行这一句时(var autofacContainer = req.App.ApplicationServices.GetAutofacRoot();)，产生如下错误，请问如何定位此问题~

Unable to retrieve Autofac root lifetime scope from service provider of type Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.

**Comment by YeLin25789** [comment]
问题已经解决了，整体跑通了。那个错误是忘记在Program，添加AutofacServiceProviderFactory。
