### ISSUE TITLE
Container.GetInstance<TService>()的使用问题

### ISSUE THREAD

**Issue by YeLin25789** [hylsabella/Easy.NetCore#2]
接口通过AutofacRegistrar注入后，我尝试再应用层使用EasyIocContainer.GetInstance()，缺无法获取注入的内容。导致报错，最后我只有使用EasyIocContainer.Container.GetService<IEasyCache>()，才成功得到。
此问题，请问是否我使用哪里不正确，找了很久没找到不对劲的地方。

**Comment by hylsabella** [comment]
AutofacRegistrar是您可以自定义一些注册，框架会自动把这里申明的注册Build到IOC容器里

https://github.com/hylsabella/EasyNetCoreDemo
您可以看下这个DEMO，这是围绕Easy.NetCore创建的整套开发框架
主要内容包括：
1、缓存（Redis + MemoryCache）
2、消息队列（RabbitMQ）
3、IOC（Autofac）
4、各自过滤器Filters
5、服务注册中心（Consul）
6、数据库操作（Dapper）
7、模型参数验证（FluentValidation）
8、定时任务（Quartz）
9、队列消费者

**Comment by hylsabella** [comment]
并不需要使用 EasyIocContainer.GetInstance()去获取类型，目前是使用属性注入的，只要在定义属性就能初始化类型
例如：public Type1 svc1 { get; set; } 
svc1 会自动注入

**Comment by YeLin25789** [comment]
好的，谢谢，我尝试一下看看
